terminate(pyenv);
clearvars;

code = sprintf(['',...
    '\n',...
    '# This is an <h1> tag\n',...
    '\n',...
    '## This is an <h2> tag\n',...
    '\n',...
    '###### This is an <h6> tag',...
    '']);

dashMd = Dcc('Markdown', {'children', code});

components = {dashMd};

% Start app
startDash(components, 8057, [], 'SOLAR');