terminate(pyenv);
clearvars;

code = sprintf(['',...
    '*This text will be italic*\n\n',...
    '_This will also be italic_\n\n\n',...
    '**This text will be bold**\n\n',...
    '__This will also be bold__\n\n',...
    '_You **can** combine them_',...
    '']);

dashMd = Dcc('Markdown', {'children', code});

components = {dashMd};

% Start app
startDash(components, 8057, [], 'SOLAR');