terminate(pyenv);
clearvars;

code = sprintf(['',...
    '\n',...
    'Inline code snippet: `my_bool = true`\n\n',...
    'Block code snippet:\n',...
    '```matlab\n\n',...
    'function output = sum(a, b)\n',...
    '    output = a+b;\n',...
    'end\n\n',...
    'sum(2,2)\n',...
    '```']);

dashMd = Dcc('Markdown', {'children', code});

components = {dashMd};

% Start app
startDash(components, 8057, [], 'SOLAR');