clear all
close all
terminate(pyenv);

% create Dash app
table_app = createApp();

a = [123;123;1234;12345;123456789];

data = table(a);

% create ui elements
uifig = uifigure('visible', 'off');
uit1 = uitable(uifig, 'ColumnName', data.Properties.VariableNames, 'Data', data, 'visible', 'off');
uit2 = uitable(uifig, 'ColumnName', data.Properties.VariableNames, 'Data', data, 'visible', 'off');
uit3 = uitable(uifig, 'ColumnName', data.Properties.VariableNames, 'Data', data, 'visible', 'off');

group = py.dash_table.Format.Group;
prefix = py.dash_table.Format.Prefix;
scheme = py.dash_table.Format.Scheme;
symbol = py.dash_table.Format.Symbol;

columns_1 = {4};
columns_1{1} = struct('id', 'a', 'name', 'Symbol',...
    'type','numeric','format',py.dash_table.Format.Format(pyargs('symbol',symbol.yes)));
columns_1{2} = struct('id', 'a', 'name', 'Symbol prefix',...
    'type','numeric',...
    'format',py.dash_table.Format.Format(pyargs('symbol',symbol.yes,'symbol_prefix','CAD$ ')));
columns_1{3} = struct('id', 'a', 'name', 'Symbol suffix',...
    'type','numeric',...
    'format',py.dash_table.Format.Format(pyargs('symbol',symbol.yes,'symbol_suffix',' CAD$')));
columns_1{4} = struct('id', 'a', 'name', 'Symbol custom',...
    'type','numeric',...
    'format',struct('specifier','$','locale',struct('symbol',{{'@','*'}})));
columns_1 = {columns_1};


columns_2 = {4};
columns_2{1} = struct('id', 'a', 'name', 'Decimal',...
    'type','numeric',...
    'format',py.dash_table.Format.Format(pyargs('decimal_delimiter',':')).scheme('f').precision(uint16(2)));
columns_2{2} = struct('id', 'a', 'name', 'Custom decimal',...
    'type','numeric',...
    'format',struct('specifier','.2f','locale',struct('decimal',':')));
columns_2{3} = struct('id', 'a', 'name', 'Group',...
    'type','numeric',...
    'format',py.dash_table.Format.Format(pyargs('group_delimiter',':','group',group.yes,'groups',uint16(2))));
columns_2{4} = struct('id', 'a', 'name', 'Custom group',...
    'type','numeric',...
    'format',struct('specifier',',','locale',struct('group',':','grouping',{{uint16(2)}})));
columns_2 = {columns_2};


columns_3 = {6};
columns_3{1} = struct('id', 'a', 'name', 'Custom numerals',...
    'type','numeric','format',struct('locale',struct('numerals',...
        {{'0','AA','b','CC','','','','77','88','99'}})));
columns_3{2} = struct('id', 'a', 'name', 'Percent symbol',...
    'type','numeric',...
    'format',struct('specifier','.2%','locale',struct('percent','@')));
columns_3{3} = struct('id', 'a', 'name', 'Group 4 digits',...
    'type','numeric',...
    'format',struct('specifier',',.0f','locale',struct('separate_4digits',false)));
columns_3{4} = struct('id', 'a', 'name', 'SI',...
    'type','numeric',...
    'format',py.dash_table.Format.Format(pyargs('si_prefix',prefix.milli)).precision(uint16(0)));
columns_3{5} = struct('id', 'a', 'name', 'SI+space',...
    'type','numeric',...
    'format',py.dash_table.Format.Format(pyargs('si_prefix',prefix.milli,'symbol',symbol.yes,'symbol_suffix',' ')).precision(uint16(0)));
columns_3{6} = struct('id', 'a', 'name', 'Explicit SI',...
    'type','numeric',...
    'format',py.dash_table.Format.Format(pyargs('si_prefix',10^-3)).precision(uint16(0)));
columns_3 = {columns_3};


uit1.UserData = struct(...
    'columns', columns_1);
uit2.UserData = struct(...
    'columns', columns_2);
uit3.UserData = struct(...
    'columns', columns_3);

dash_table1 = ui2dash(uit1, 'table1');
dash_table2 = ui2dash(uit2, 'table2');
dash_table3 = ui2dash(uit3, 'table3');

br = py.dash_html_components.Br;

% add table to Dash app layout
table_app.layout = addLayout(dash_table1, br, dash_table2, br, dash_table3);

% run the app
table_app.run_server(pyargs('debug',true,'use_reloader',false,'port','8057'))