terminate(pyenv);
clearvars;

sequences = {struct(...
    'sequence', 'AUGGGCCCGGGCCCAAUGGGCCCGGGCCCA',...
    'structure', '.((((((())))))).((((((()))))))',...
    'options', struct(...
        'applyForce', true,...
        'circularizeExternal', true,...
        'avoidOthers', true,...
        'labelInterval', 5,...
        'name', 'PDB_01019'))};

component = dashBio('FornaContainer', {...
        'id', 'my-dashbio-fornacontainer',...
        'sequences', sequences});  
    
components = {component};

% Run the app
startDash(components, 8057);