terminate(pyenv);
clearvars;

df = readBioData('https://git.io/Ja6zV', 'dataframe',...
    {'sep', '\t', 'skiprows', int8(4)}).set_index('model');
data = df.values;

cols = py.list(df.columns.values);
row_labels = py.list(df.index.values);

component = Dcc('Graph',{...
    'figure', dashBio(...
        'Clustergram',{...
            'data', data,...
            'color_threshold', struct(...
                'row', 150,...
                'col', 700),...
            'column_labels', cols,...
            'row_labels', row_labels,...
            'hidden_labels', {'row'},...
            'width', 600})});  
    
components = {component};

% Run the app
startDash(components, 8057);