terminate(pyenv);
clearvars;

df = readBioData('https://git.io/Ja6zV', 'dataframe',...
    {'sep', '\t', 'skiprows', int8(4)}).set_index('model');
data = df.values;

cols = py.list(df.columns.values);
rowLabels = py.list(df.index.values);

clustergram = dashBio(...
        'Clustergram',{...
            'data', data,...
            'row_labels', rowLabels,... 
            'column_labels', cols,...            
            'color_threshold', struct(...
                'row', 250,...
                'col', 700),...
            'height', 800,...
            'width', 700,...
            'hidden_labels', 'row',...
            'col_group_marker', py.list({...
                struct('group', 1,...
                    'annotation', 'largest column cluster',...
                    'color', '#EF553B')}),...
            'row_group_marker', py.list({...
                struct('group', 2,...
                    'annotation', 'cluster 2',...
                    'color', '#AB63FA'),...
                struct('group', 1,...
                    'annotation', '',...
                    'color', '#19D3F3')})});

component = Dcc('Graph',{...
    'figure', clustergram});  
    
components = {component};

% Run the app
startDash(components, 8057);