terminate(pyenv);
clearvars;

component = dashBio('Pileup', {...
        'id', 'pileup-genome',...
        'range', struct(...
            'contig', 'chr8',...
            'start', 65869361,...
            'stop', 65869511),...
        'reference', struct(...
            'label', 'mm10',...
            'url', 'https://hgdownload.cse.ucsc.edu/goldenPath/mm10/bigZips/mm10.2bit')});            

components = {component};

% Run the app
startDash(components, 8057);