terminate(pyenv);
clearvars;

% Read data file
data = readBioData('https://git.io/JVz8X');
data = jsondecode(data);

component = dashBio('Pileup', {...
        'id', 'tracks-pileup',...
        'range', struct(...
            'contig', 'chr1',...
            'start', 4930382,...
            'stop', 4946898),...
        'reference', struct(...
            'label', 'hg19',...
            'url', 'https://hgdownload.cse.ucsc.edu/goldenPath/hg19/bigZips/hg19.2bit'),...
        'tracks', {...
            struct(...
                'viz', 'coverage',...
                'label', 'alignments',...
                'source', 'alignmentJson',...
                'sourceOptions', data),...
            struct(...
                'viz', 'pileup',...
                'label', 'alignments',...
                'source', 'alignmentJson',...
                'sourceOptions', data)}});
            

components = {component};

% Run the app
startDash(components, 8057);