terminate(pyenv);
clearvars;

% Read data file
data = readBioData('https://git.io/J2Bgu');
circos_graph_data = jsondecode(char(data));

component = dashBio('Circos', {...
        'id', 'my-dashbio-circos',...
        'layout', circos_graph_data.('GRCh37'),...
        'tracks', {struct(...
            'type', 'CHORDS',...
            'data', circos_graph_data.('chords'),...
            'opacity', 0.7,...
            'color', struct('name', 'color'),...
            'config', struct(...
                'tooltipContent', struct(...
                    'source', 'source',...
                    'sourceID', 'id',...
                    'target', 'target',...
                    'targetID', 'id',...
                    'targetEnd', 'end')))}});
    
components = {component};

% Run the app
startDash(components, 8057);