terminate(pyenv);
clearvars;

dashTextarea = Dcc('Textarea', {...
    'id', 'textarea_id',...
    'value', 'Copy and paste here',...
    'style', struct('height', 100)});

dashClipboard = Dcc('Clipboard', {...
    'target_id', 'textarea_id',...
    'title', 'copy',...
    'style', struct(...
        'display', 'inline-block',...
        'fontSize', 20,...
        'verticalAlign', 'top')});

components = {dashTextarea, dashClipboard};

% Start app
startDash(components, 8057, [], 'SOLAR');