terminate(pyenv);
clearvars;

% Read data file
data = readtable('https://git.io/JgqCd', 'PreserveVariableNames', true);

% Create ui elements
uiFigure = uifigure('visible', 'off');
size = [12, 12];
uiGrid = uigridlayout(uiFigure, size);

dataTable = uitable(uiGrid, 'ColumnName', data.Properties.VariableNames,...
    'Data', data, 'visible', 'off', 'Tag', 'datatable-interactivity');

lncols = width(data);
columns = {lncols};
for i=1:lncols
    columns{i} = struct(...
        'name', string(dataTable.ColumnName(i)),...
        'id', string(dataTable.ColumnName(i)),...
        'deletable', true,...
        'selectable', true);
end
columns = {columns};

dataTable.UserData = struct(...
    'columns', columns,...
    'editable', true,...
    'filter_action', 'native',...
    'sort_action', 'native',...
    'sort_mode', 'multi',...
    'column_selectable', 'multi',...
    'row_selectable', 'multi',...
    'row_deletable', true,...
    'selected_columns', py.list({}),...
    'selected_rows', py.list({}),...
    'page_action', 'native',...
    'page_current', 0,...
    'page_size', 10);

% Initial Plot
ax = axes(uiGrid);
ax.Tag = 'datatable-interactivity-container';

% Callbacks
argsStyles = {...
    argsOut('datatable-interactivity','style_data_conditional'),...
    argsIn('datatable-interactivity','selected_columns')};
handleStyles = 'update_styles';

callbackDat = {argsStyles, handleStyles};

argsGraphs = {...
    argsOut('datatable-interactivity-container','figure'),...
    argsIn('datatable-interactivity','derived_virtual_data'),...
    argsIn('datatable-interactivity','derived_virtual_selected_rows')};
handleGraphs = 'update_graphs';

callbackDat{2,1} = argsGraphs;
callbackDat{2,2} = handleGraphs;

% Run the app
startDash(uiGrid, 8057, callbackDat);