terminate(pyenv);
clearvars;

% Read data file
data = readBioData('https://git.io/JVRcs');
mdata = jsondecode(char(data));

component = dashBio('NeedlePlot', {...
        'mutationData', mdata,...
        'needleStyle', struct(...
            'stemColor', '#FF888',...
            'stemThickness', 2,...
            'stemConstHeight', true,...
            'headSize', 10,...
            'headColor', {{'#FFDD00', '#000000'}})});
    
components = {component};

% Run the app
startDash(components, 8057);