terminate(pyenv);
clearvars; % Removes all variables from the currently active workspace.

markdown_text = sprintf([...
    '### Dash and Markdown\n'...
    '\n'...
    'Dash apps can be written in Markdown.\n'...
    'Dash uses the [CommonMark](http://commonmark.org/)\n'...
    'specification of Markdown.\n'...
    'Check out their [60 Second Markdown Tutorial](http://commonmark.org/help/)\n'...
    'if this is your first introduction to Markdown!'
]);

myMarkdown = Html('Div', {Dcc('Markdown', {...
    'children', markdown_text})});

components = {myMarkdown};

% Run the app.
layoutApp = startDash(components, 8057, [], 'LUX');