terminate(pyenv);
clearvars;

myChecklist = Dcc('Checklist', {...
    'options', {...
        struct('label', 'New York City', 'value', 'NYC'),...
        struct('label', 'Montréal', 'value', 'MTL'),...
        struct('label', 'San Francisco', 'value', 'SF')},...
    'value', {'NYC', 'MTL'},...
    'labelStyle', struct('display', 'inline-block')});

components = {myChecklist};

% Start app
startDash(components, 8057, [], 'SOLAR');
