terminate(pyenv);
clearvars;

myRadioitems = Dcc('RadioItems', {...
    'options', {...
        struct('label', 'New York City', 'value', 'NYC'),...
        struct('label', 'Montréal', 'value', 'MTL'),...
        struct('label', 'San Francisco', 'value', 'SF')},...
    'value', 'MTL',...
    'labelStyle', struct('display', 'flex')});

components = {myRadioitems};

% Start app
startDash(components, 8057, [], 'SOLAR');
