terminate(pyenv);
clearvars;

dashDropdown = Dcc('Dropdown', {...
    'options', {...
        struct('label', 'New York City', 'value', 'NYC'),...
        struct('label', 'Montréal', 'value', 'MTL'),...
        struct('label', 'San Francisco', 'value', 'SF')},...
    'value', {'NYC', 'MTL'},...
    'multi', true});

components = {dashDropdown};

% Start app
startDash(components, 8057, [], 'SOLAR');