function output = update_output(n_clicks, input1, input2)
    output = jsonencode({...
        sprintf('The button has been pressed %s times, Input 1 is "%s", and Input 2 is "%s"',...
        string(n_clicks), input1, input2)});
end