clear all
close all
terminate(pyenv);

% read data file
data = readtable('condForm1.csv', 'PreserveVariableNames', true);

data.id = (0:height(data)-1).'; % Add index column, starting from 0

% create Dash app
table_app = createApp();

% create ui elements
uifig = uifigure('visible', 'off');
uit = uitable(uifig, 'ColumnName', data.Properties.VariableNames, 'Data', data, 'visible', 'off');

[~, lncols] = size(uit.Data);
columns = {lncols};
columns{1} = struct('name', 'Date', 'id', 'Date', 'type', 'datetime', 'editable', false);
columns{2} = struct('name', 'Delivery', 'id', 'Delivery', 'type', 'datetime');
columns{3} = struct('name', 'Region', 'id', 'Region', 'type', 'text');
columns{4} = struct('name', 'Temperature', 'id', 'Temperature', 'type', 'numeric');
columns{5} = struct('name', 'Humidity', 'id', 'Humidity', 'type', 'numeric');
columns{6} = struct('name', 'Pressure', 'id', 'Pressure', 'type', 'any');
columns = {columns};

style_data_conditional = {9};
style_data_conditional{1} = struct(...
    'if', struct('column_id', 'Region'),...
    'backgroundColor', 'dodgerblue',...
    'color', 'white');
style_data_conditional{2} = struct(...
    'if', struct('filter_query', '{Humidity} > 19 && {Humidity} < 41',...
        'column_id', 'Humidity'),...
    'backgroundColor', 'tomato',...
    'color', 'white');
style_data_conditional{3} = struct(...
    'if', struct('column_id', 'Pressure',...
        'filter_query', sprintf('{Pressure} = %d', max(data.Pressure))),...
    'backgroundColor', '#85144b',...
    'color', 'white');
style_data_conditional{4} = struct(...
    'if', struct('row_index', 5, 'column_id', 'Region'),...
    'backgroundColor', 'hotpink',...
    'color', 'white');
style_data_conditional{5} = struct(...
    'if', struct('filter_query', '{id} = 4', 'column_id', 'Region'),...
    'backgroundColor', 'RebeccaPurple');
style_data_conditional{6} = struct(...
    'if', struct('filter_query', '{Delivery} > {Date}', 'column_id', 'Delivery'),...
    'backgroundColor', '#3D9970');
style_data_conditional{7} = struct(...
    'if', struct('column_editable', false),...
    'backgroundColor', 'rgb(240, 240, 240)',...
    'cursor', 'not_allowed');
style_data_conditional{8} = struct(...
    'if', struct('column_type', 'text'),...
    'textAlign', 'left');
style_data_conditional{9} = struct(...
    'if', struct('state', 'active'),...
    'backgroundColor', 'rgba(0, 116, 217, 0.3)',...
    'border', '1px solid rgb(0, 116, 217)');

style_data_conditional = {style_data_conditional};

uit.UserData = struct(...
    'sort_action', 'native',...
    'columns', columns,...
    'editable', true,...
    'style_data_conditional', style_data_conditional);

dash_table = ui2dash(uit, 'table');

% add table to Dash app layout
table_app.layout = addLayout(dash_table);

% run the app
table_app.run_server(pyargs('debug',true,'use_reloader',false,'port','8057'))