function cols = update_columns(n_clicks, value, existing_columns)
    if n_clicks > 0
        existing_columns{end+1} = struct(...
            'id', value,...
            'name', value,...
            'renamable', true,...
            'deletable', true);
    end
    cols = jsonencode(existing_columns);
end